### ISSUE TITLE
multiuser available  ? 

### ISSUE THREAD

**Issue by mickadoua** [KartoffelToby/docker-nas-samba#1]
hi, thanks for your project very helpfull, 
my idea is to add on existant docker machine, a NAS as simple as possible 

no anonymous connection 
5 / 6 users 
all users can add / delete  on commun folder, 
all users have a private folder

i can create, a shared folder for an user
how can I edit your script start.sh, with multi user / folder  support ?

thank you

**Comment by KartoffelToby** [comment]
@mickadoua Thanks for your feedback!

I'll check this in the next days
